CREATE DATABASE TAREA

USE TAREA

GO

CREATE TABLE DOCTOR(
	IdDoctor INT IDENTITY(100000,1) PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL,
	Apellidos VARCHAR(100) NOT NULL,
	FechaNacimiento DATE NOT NULL,
	Sexo char(1) NOT NULL
	)
GO

GO
CREATE TABLE ESPECIALIDAD(
	CodEspecialidad CHAR(6) PRIMARY KEY,
	NomEspecialidad VARCHAR(200) NOT NULL,
	DesEspecialidad VARCHAR(500) NOT NULL,
)
GO

GO
CREATE TABLE ENFERMEDAD(
	CodEnfermedad CHAR (6) PRIMARY KEY,
	NomEnfermedad VARCHAR(200) NOT NULL,
	DesEnfermedad VARCHAR(500) NOT NULL,
)
GO